"""
build.py
========
Cross-platform build script for Ambilight Desktop. Produces, for the host OS:

  1. A PyInstaller ``--onedir`` bundle of the Python service, named
     ``ambilight-service`` (the name the Electron shell looks for under
     ``resources/service/``).
  2. The Electron installer for the host OS via electron-builder
     (NSIS on Windows, DMG on macOS, AppImage + deb on Linux).

Usage:
    python build.py              # service + UI for the current OS
    python build.py --service    # service only
    python build.py --ui         # UI only

Requirements: Python 3.11+ with PyInstaller; Node 20+ with pnpm.
"""

from __future__ import annotations

import argparse
import os
import platform
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
DIST = ROOT / "dist"
SERVICE_DIST = DIST / "service"
UI_DIR = ROOT / "ui"

SERVICE_NAME = "ambilight-service"
SYSTEM = platform.system()  # Windows | Darwin | Linux


def _which(name: str) -> str:
    """Resolve *name* to a runnable path, honouring Windows shims.

    Python's subprocess on Windows only auto-resolves bare names to ``.exe``, so
    a Node tool installed as ``pnpm.cmd``/``.bat`` (with no ``.exe``) is invisible
    to ``subprocess.run([name])`` and raises FileNotFoundError. ``shutil.which``
    consults PATHEXT and finds the shim; passing its full path runs it correctly.
    Falls back to *name* unchanged so POSIX behaviour is identical.
    """
    return shutil.which(name) or name


def _run(cmd: list[str], cwd: Path | None = None) -> None:
    print(f"\n{'=' * 60}\n  Running: {' '.join(cmd)}\n  CWD:     {cwd or ROOT}\n{'=' * 60}\n")
    result = subprocess.run([_which(cmd[0]), *cmd[1:]], cwd=str(cwd or ROOT))
    if result.returncode != 0:
        print(f"\n[FATAL] Command failed with exit code {result.returncode}")
        sys.exit(result.returncode)


def _check_tool(name: str, version_flag: str = "--version") -> None:
    try:
        subprocess.run([_which(name), version_flag], capture_output=True, check=True)
    except (FileNotFoundError, OSError):
        print(f"[FATAL] Required tool not found on PATH: {name}")
        sys.exit(1)


def _check_version_sync() -> str:
    """Sync and validate version across all components.

    The VERSION file at the repo root is the single source of truth. This function:
    1. Reads VERSION (canonical)
    2. Syncs to ui/package.json (already done by npm, but double-check)
    3. Syncs to ambilight/_version.py (for PyInstaller bundles)
    
    Returns the agreed version string.
    """
    import json
    import re

    # Read VERSION file (single source of truth)
    version_file = ROOT / "VERSION"
    canonical_version = version_file.read_text(encoding="utf-8").strip()
    if not canonical_version:
        print("[FATAL] VERSION file is empty")
        sys.exit(1)

    # Validate semver format
    if not re.match(r"^\d+\.\d+\.\d+$", canonical_version):
        print(f"[FATAL] Invalid version format in VERSION file: {canonical_version}")
        print("        Expected format: X.Y.Z (semver)")
        sys.exit(1)

    # Check package.json version
    pkg_path = UI_DIR / "package.json"
    pkg_version = json.loads(pkg_path.read_text(encoding="utf-8"))["version"]

    if pkg_version != canonical_version:
        print(
            f"[WARN] Version mismatch: VERSION={canonical_version!r} but "
            f"ui/package.json={pkg_version!r}. Run 'node scripts/sync-version.mjs' "
            f"to sync, then rebuild."
        )
        sys.exit(1)

    # Sync to ambilight/_version.py (for PyInstaller bundles)
    version_py = ROOT / "ambilight" / "_version.py"
    version_py_content = (
        "# This file is auto-generated by build.py from the VERSION file.\n"
        "# Do not edit manually. Update VERSION file at the repo root instead.\n"
        f'__version__ = "{canonical_version}"\n'
    )
    old_content = version_py.read_text(encoding="utf-8") if version_py.exists() else ""
    if old_content != version_py_content:
        version_py.write_text(version_py_content, encoding="utf-8")
        print(f"[OK] Synced version to ambilight/_version.py: {canonical_version}")
    
    print(f"[OK] Version in sync: {canonical_version}")
    return canonical_version


def build_service(gpu: bool = False) -> None:
    print(f"\n[1/2] Building Python service with PyInstaller ({'GPU' if gpu else 'lean CPU'})…")
    _check_tool("pyinstaller")

    if SERVICE_DIST.exists():
        shutil.rmtree(SERVICE_DIST)
    SERVICE_DIST.mkdir(parents=True, exist_ok=True)

    hidden_imports = [
        "--hidden-import=mss",
        "--hidden-import=numpy",
        "--hidden-import=PIL",
        "--hidden-import=yaml",
        "--hidden-import=uvicorn",
        "--hidden-import=fastapi",
        "--hidden-import=pydantic",
    ]
    # Probe availability WITHOUT importing — importing winsdk/comtypes/
    # windows_capture here would fight over the COM apartment and crash the build.
    import importlib.util
    def _available(name: str) -> bool:
        try:
            return importlib.util.find_spec(name) is not None
        except Exception:
            return False

    # The capture backends are REQUIRED on Windows. Shipping without them
    # silently degrades every install to MSS — fullscreen games / overlay video
    # render black, and a transient MSS failure (screen lock, display sleep) has
    # nothing to fail over to, which is exactly the "All backends exhausted" loop
    # users hit. Fail the build loudly rather than producing an MSS-only installer
    # (these are pinned in requirements.txt under the Windows markers).
    # cv2 (opencv-python) is included: windows_capture imports it at module load
    # and dxcam uses it for colour conversion — without it BOTH WGC and DXGI fail
    # and every install is stranded on MSS. It is a hard dependency of
    # windows-capture, so installing the requirements already pulls it in.
    if SYSTEM == "Windows":
        required_caps = ["mss", "windows_capture", "dxcam", "comtypes", "cv2"]
        missing = [p for p in required_caps if not _available(p)]
        if missing:
            print(
                f"[FATAL] Required capture dependency(ies) missing from the build "
                f"environment: {', '.join(missing)}.\n"
                f"        Install them so the installer ships every backend:\n"
                f"          pip install windows-capture dxcam comtypes mss opencv-python"
            )
            sys.exit(1)

    # Always-bundled optional deps: capture backends + audio + WGC, and the
    # smart-home integration stack (paho-mqtt + keyring) when present.
    optional = ["dxcam", "winsdk", "comtypes", "soundcard", "windows_capture", "paho", "keyring"]
    collect_all: list[str] = []
    # winsdk is collected in full: its WinRT namespaces (e.g.
    # winsdk.windows.ui.notifications.management for Notification Flash) are
    # imported dynamically, so a bare --hidden-import misses them. dxcam + comtypes
    # are collected in full too: dxcam imports dxcam.core.* submodules dynamically
    # and drives the display via comtypes-generated COM wrappers, which a bare
    # --hidden-import leaves out — so the frozen DXGI backend fails to import.
    for pkg in ("windows_capture", "dxcam", "comtypes", "soundcard", "paho", "keyring", "winsdk"):
        if _available(pkg):
            collect_all += ["--collect-all", pkg]

    # Lean build: drop the heavy GPU stack (CuPy ~118 MB + CUDA ~86 MB) and obvious
    # dead weight. OpenCV (cv2) is NOT dropped on Windows — the WGC backend's
    # windows_capture imports cv2 at module load and dxcam uses it for colour
    # conversion, so excluding it silently broke WGC+DXGI and stranded installs on
    # MSS (cv2 also gives _cpu_resize a faster path than Pillow). Off Windows there
    # is no native capture backend (MSS is pure-Python), so cv2 stays excluded to
    # keep the bundle lean. GPU build (--gpu) re-includes CuPy for CUDA users.
    excludes = ["tkinter", "_tkinter", "lib2to3", "pydoc_data", "matplotlib", "PyQt5", "PySide2"]
    bundle_cv2 = (SYSTEM == "Windows" or gpu) and _available("cv2")
    if bundle_cv2:
        collect_all += ["--collect-all", "cv2"]
        optional.append("cv2")
    else:
        excludes.append("cv2")
    if gpu:
        optional += ["cupy", "torch"]
        if _available("cupy"):
            collect_all += ["--collect-all", "cupy"]
    else:
        excludes += ["cupy", "cupyx", "cupy_backends", "torch", "nvidia"]

    for opt in optional:
        if _available(opt):
            hidden_imports.append(f"--hidden-import={opt}")

    exclude_args: list[str] = []
    for mod in excludes:
        exclude_args += ["--exclude-module", mod]

    sep = os.pathsep  # ; on Windows, : elsewhere
    _run([
        "pyinstaller",
        "--noconfirm",
        "--onedir",
        # Build a windowed (no-console) binary. The service is a background
        # process supervised by the Electron shell / launched via the Startup
        # launcher — a console subsystem exe (PyInstaller's default) pops up a
        # terminal window on every launch that neither `windowsHide` nor
        # `start /min` can suppress. stdout/stderr still reach the Electron
        # capture log because the supervisor passes real file handles for fd
        # 1/2; service_entry.py rebinds sys.stdout/err to them when frozen.
        "--windowed",
        "--name", SERVICE_NAME,
        "--distpath", str(SERVICE_DIST),
        "--specpath", str(DIST / "build_spec"),
        "--workpath", str(DIST / "build_work"),
        "--add-data", f"{ROOT / 'configuration.yaml'}{sep}.",
        "--add-data", f"{ROOT / 'profiles'}{sep}profiles",
        # Collect the whole package so conditionally/dynamically imported
        # submodules (capture backends, api_server referenced via uvicorn) ship.
        "--collect-submodules", "ambilight",
        *exclude_args,
        *collect_all,
        *hidden_imports,
        str(ROOT / "service_entry.py"),
    ])
    print(f"\n[OK] Service built: {SERVICE_DIST / SERVICE_NAME}")

    # Post-build bundling check: confirm every required capture backend was
    # actually collected into the onedir, before an installer is ever produced.
    # This is a *filesystem* check, not an import/open — WGC (WinRT) and DXGI need
    # an interactive desktop + GPU to load, which a headless CI runner doesn't
    # have, so running the frozen exe there gives false failures. The bundling
    # guarantee we care about is simply that the modules shipped; whether they can
    # capture is a runtime concern verified by `ambilight-service --selfcheck` on a
    # real machine.
    missing = _missing_bundled_backends(SERVICE_DIST / SERVICE_NAME)
    if missing:
        print(
            f"[FATAL] Capture backend(s) missing from the bundle: {', '.join(missing)}.\n"
            f"        The installer would ship MSS-only. Check the --collect-all / "
            f"--hidden-import flags above for these packages."
        )
        sys.exit(1)
    print("[OK] All required capture backends are bundled.")


def _missing_bundled_backends(bundle_root: Path) -> list[str]:
    """Return the binary capture-backend packages that did NOT make it into the
    onedir.

    Filesystem-only (no import) so it works on a headless build box. We check the
    Windows fast-capture backends specifically because they're the ones that
    silently went missing before (optional, native, ``--collect-all``'d) and that
    leave users on MSS. They ship as extracted ``_internal/<pkg>/`` directories
    (native ``.pyd`` / data), so a missing directory means a dropped backend.

    Pure-Python ``mss`` is deliberately not checked here: as a plain
    ``--hidden-import`` it's compiled into the PYZ archive rather than extracted to
    disk, so it's invisible to a filesystem scan. Its presence is already
    guaranteed by the hardcoded ``--hidden-import=mss`` plus the build-env check
    above, and the test suite imports it."""
    if SYSTEM != "Windows":
        return []  # no native fast-capture backends off Windows; MSS is in the PYZ
    # cv2 is included because windows_capture/dxcam need it — a dropped cv2 is what
    # silently broke WGC+DXGI before, so guard it like a backend.
    required = ["windows_capture", "dxcam", "comtypes", "cv2"]

    missing: list[str] = []
    for imp in required:
        hits = list(bundle_root.rglob(imp)) + list(bundle_root.rglob(f"{imp}.*"))
        bundled = any(
            h.is_dir() or h.suffix in {".pyd", ".so", ".dll", ".py", ".pyc"}
            for h in hits
        )
        if not bundled:
            missing.append(imp)
    return missing


def build_ui() -> None:
    print("\n[2/2] Building Electron UI with electron-builder…")
    _check_tool("pnpm")

    _run(["pnpm", "install", "--frozen-lockfile"], cwd=UI_DIR)
    _run(["pnpm", "run", "build"], cwd=UI_DIR)

    target_flag = {"Windows": "--win", "Darwin": "--mac", "Linux": "--linux"}.get(SYSTEM, "--linux")
    _run(["pnpm", "exec", "electron-builder", target_flag], cwd=UI_DIR)
    print(f"\n[OK] UI built. See {UI_DIR / 'release'}")


def main() -> None:
    parser = argparse.ArgumentParser(description="Build Ambilight Desktop (cross-platform)")
    parser.add_argument("--service", action="store_true", help="Build service only")
    parser.add_argument("--ui", action="store_true", help="Build UI only")
    parser.add_argument("--gpu", action="store_true",
                        help="Bundle CuPy/CUDA + OpenCV (large GPU build). Default is lean CPU-only.")
    args = parser.parse_args()

    # Single-source-of-truth version gate — keeps the service binary and the
    # installer/updater feed reporting the same version.
    _check_version_sync()

    build_all = not args.service and not args.ui
    if build_all or args.service:
        build_service(gpu=args.gpu)
    if build_all or args.ui:
        build_ui()

    if build_all:
        print("\n" + "=" * 60)
        print("  BUILD COMPLETE")
        print(f"  Service: {SERVICE_DIST / SERVICE_NAME}")
        print(f"  UI:      {UI_DIR / 'release'}")
        print("=" * 60)


if __name__ == "__main__":
    main()
