blank_issues_enabled: false

contact_links:
  - name: Questions & Community Discussions
    url: https://github.com/LMC4910/ambilightRepo/discussions
    about: Ask questions, get help, and discuss ideas.