const { app, BrowserWindow, ipcMain, shell, Tray, Menu, nativeImage, dialog } = require('electron')
const path = require('path')
const fs = require('fs')
const os = require('os')
const { spawn } = require('child_process')
const WebSocket = require('ws')
const { autoUpdater } = require('electron-updater')

// Window / taskbar title shown to the user.
const APP_TITLE = 'Ambient';
// Group under our own identity in the Windows taskbar (matches build.appId).
app.setAppUserModelId('com.ambilight.desktop');

const AMBILIGHT_DIR = path.join(os.homedir(), '.ambilight');
const LOG_DIR = path.join(AMBILIGHT_DIR, 'logs');
const LOG_FILE = path.join(LOG_DIR, 'ambilight.log');
const SERVICE_OUT_LOG = path.join(LOG_DIR, 'service.out.log');
const TOKEN_PATH = path.join(AMBILIGHT_DIR, 'auth_token');
const ONBOARDED_MARKER = path.join(AMBILIGHT_DIR, 'onboarded');
const WINDOW_STATE_PATH = path.join(AMBILIGHT_DIR, 'window.json');

// --- Window bounds persistence + visibility signalling ---
let _saveBoundsTimer = null;
function loadWindowState() {
  try { return JSON.parse(fs.readFileSync(WINDOW_STATE_PATH, 'utf8')); } catch (_) { return null; }
}
function saveWindowState() {
  if (!mainWindow || mainWindow.isDestroyed() || mainWindow.isMinimized()) return;
  clearTimeout(_saveBoundsTimer);
  _saveBoundsTimer = setTimeout(() => {
    try {
      if (!fs.existsSync(AMBILIGHT_DIR)) fs.mkdirSync(AMBILIGHT_DIR, { recursive: true });
      fs.writeFileSync(WINDOW_STATE_PATH, JSON.stringify(mainWindow.getBounds()));
    } catch (_) { /* ignore */ }
  }, 500);
}
function sendVisibility(visible) {
  if (mainWindow && !mainWindow.isDestroyed()) {
    mainWindow.webContents.send('window:visibility', visible);
  }
}

// Branded app icon, shipped under electron/assets (generated by scripts/gen-icons.mjs).
// Used for the tray and the BrowserWindow on Windows/Linux.
const APP_ICON_PATH = path.join(__dirname, 'assets', 'icon.png');
function appIcon() {
  const img = nativeImage.createFromPath(APP_ICON_PATH);
  return img.isEmpty() ? undefined : img;
}

// REST and WebSocket share one port (the service mounts /ws on the API app).
const API_PORT = 7826;
const API_URL = `http://127.0.0.1:${API_PORT}`;
const WS_URL = `ws://127.0.0.1:${API_PORT}/ws`;
const HEALTH_INTERVAL_MS = 5000;

let mainWindow = null;
let tray = null;
let isQuitting = false;
let wsClient = null;
let authToken = null;
let wsReconnectTimer = null;

// --- Service supervision state ---
let serviceProc = null;       // child process we spawned (null if external)
let serviceShouldRun = true;  // whether the service is meant to be running
let healthTimer = null;
let lastStatus = null;

// --- Auto-update state ---
let lastUpdateState = { state: 'idle' };  // forwarded to the renderer + tray

// ---------------------------------------------------------------------------
// Auth token
// ---------------------------------------------------------------------------
function getAuthToken(forceReread = false) {
  // The service regenerates its token on every (re)start, so re-read from disk
  // whenever asked rather than trusting a possibly-stale cached value.
  if (authToken && !forceReread) return authToken;
  try {
    if (fs.existsSync(TOKEN_PATH)) {
      authToken = fs.readFileSync(TOKEN_PATH, 'utf8').trim();
    }
  } catch (err) {
    console.error("Failed to read auth token:", err);
  }
  return authToken;
}

async function fetchApi(endpoint, options = {}, _retried = false) {
  const token = getAuthToken();
  if (!token) {
    throw new Error("Service Offline or Unauthorized");
  }
  const res = await fetch(`${API_URL}${endpoint}`, {
    ...options,
    headers: {
      ...options.headers,
      'Authorization': `Bearer ${token}`,
      'Content-Type': 'application/json'
    }
  });
  if (!res.ok) {
    // Token may be stale after a service restart — re-read once and retry.
    if ((res.status === 401 || res.status === 403) && !_retried) {
      getAuthToken(true);
      return fetchApi(endpoint, options, true);
    }
    throw new Error(`API Error: ${res.status} ${res.statusText}`);
  }
  return await res.json();
}

// ---------------------------------------------------------------------------
// Python service lifecycle
// ---------------------------------------------------------------------------
function resolveServiceCommand() {
  // Production: a bundled PyInstaller binary shipped under resources/service.
  const exeName = process.platform === 'win32' ? 'ambilight-service.exe' : 'ambilight-service';
  const bundled = path.join(process.resourcesPath || '', 'service', exeName);
  if (fs.existsSync(bundled)) {
    return { cmd: bundled, args: [], cwd: path.dirname(bundled) };
  }

  // Development: run the module from the repo with the local venv if present.
  const repoRoot = path.join(__dirname, '..', '..');
  const venvPy = process.platform === 'win32'
    ? path.join(repoRoot, '.venv', 'Scripts', 'python.exe')
    : path.join(repoRoot, '.venv', 'bin', 'python');
  const python = fs.existsSync(venvPy) ? venvPy : (process.platform === 'win32' ? 'python' : 'python3');
  return { cmd: python, args: ['-m', 'ambilight.service'], cwd: repoRoot };
}

// Open an append fd to capture the service's stdout/stderr. Without this the
// service is spawned with stdio 'ignore', so a Python traceback or a crash
// before logging is configured (e.g. the parent process failing to start the
// pipeline worker) is completely invisible. Truncate if it has grown large —
// this is a boot/crash capture, not the rotating app log.
function openServiceLogFd() {
  try {
    if (!fs.existsSync(LOG_DIR)) fs.mkdirSync(LOG_DIR, { recursive: true });
    try {
      const st = fs.statSync(SERVICE_OUT_LOG);
      if (st.size > 5 * 1024 * 1024) fs.truncateSync(SERVICE_OUT_LOG, 0);
    } catch (_) { /* file may not exist yet */ }
    const fd = fs.openSync(SERVICE_OUT_LOG, 'a');
    fs.writeSync(fd, `\n===== service spawn ${new Date().toISOString()} =====\n`);
    return fd;
  } catch (err) {
    console.error('[Service] Could not open capture log:', err.message);
    return null;
  }
}

function spawnService() {
  if (serviceProc) return;
  const { cmd, args, cwd } = resolveServiceCommand();
  console.log('[Service] Spawning:', cmd, args.join(' '), 'cwd=', cwd);
  const logFd = openServiceLogFd();
  // Route stdout+stderr to the capture file (fall back to 'ignore' if it could
  // not be opened) so crashes/tracebacks are always recoverable.
  const stdio = logFd !== null ? ['ignore', logFd, logFd] : 'ignore';
  try {
    serviceProc = spawn(cmd, args, { cwd, env: process.env, stdio, windowsHide: true });
  } catch (err) {
    console.error('[Service] Failed to spawn:', err.message);
    if (logFd !== null) { try { fs.closeSync(logFd); } catch (_) {} }
    serviceProc = null;
    return;
  }
  // The child has inherited the fd; close our copy so we don't leak descriptors.
  if (logFd !== null) { try { fs.closeSync(logFd); } catch (_) {} }
  // Token is regenerated on each service start — drop the cached one.
  authToken = null;

  serviceProc.on('exit', (code, signal) => {
    console.log(`[Service] Exited (code=${code}, signal=${signal})`);
    serviceProc = null;
    // Watchdog: relaunch if it died unexpectedly.
    if (serviceShouldRun) {
      setTimeout(() => { if (serviceShouldRun && !serviceProc) spawnService(); }, 1500);
    }
  });
  serviceProc.on('error', (err) => {
    console.error('[Service] Process error:', err.message);
  });
}

async function isServiceHealthy() {
  try {
    const res = await fetch(`${API_URL}/health`, { signal: AbortSignal.timeout(2000) });
    return res.ok;
  } catch {
    return false;
  }
}

async function startService() {
  serviceShouldRun = true;
  // If something is already serving /health (e.g. a manually started service),
  // adopt it instead of spawning a duplicate.
  if (await isServiceHealthy()) {
    console.log('[Service] Existing healthy service detected; adopting it.');
    return;
  }
  spawnService();
}

function stopService() {
  serviceShouldRun = false;
  if (serviceProc) {
    try { serviceProc.kill(); } catch (_) {}
    serviceProc = null;
  }
}

async function restartService() {
  // Prefer an in-process pipeline restart when the API is reachable; otherwise
  // bounce the whole process.
  try {
    await fetchApi('/api/service/restart', { method: 'POST' });
    return;
  } catch (_) {
    stopService();
    setTimeout(startService, 500);
  }
}

function setStatus(status) {
  if (status === lastStatus) return;
  lastStatus = status;
  if (mainWindow && !mainWindow.isDestroyed()) {
    mainWindow.webContents.send('service:status', status);
  }
  updateTray();
}

// ---------------------------------------------------------------------------
// System tray
// ---------------------------------------------------------------------------
function showWindow() {
  if (!mainWindow || mainWindow.isDestroyed()) {
    createWindow();
  } else {
    mainWindow.show();
    mainWindow.focus();
  }
}

function updateTray() {
  if (!tray) return;
  const label = lastStatus === 'connected' ? 'Service: Online'
    : lastStatus === 'connecting' ? 'Service: Connecting…' : 'Service: Offline';
  tray.setToolTip(`Ambilight — ${label}`);
  const menu = Menu.buildFromTemplate([
    { label, enabled: false },
    { type: 'separator' },
    { label: 'Open Ambilight', click: showWindow },
    { label: 'Start', click: () => startService(), enabled: lastStatus !== 'connected' },
    { label: 'Stop', click: () => { stopService(); setStatus('disconnected'); }, enabled: lastStatus !== 'disconnected' },
    { label: 'Restart', click: () => restartService() },
    { type: 'separator' },
    {
      label: lastUpdateState.state === 'downloaded' ? 'Restart to Update' : 'Check for Updates…',
      click: () => (lastUpdateState.state === 'downloaded' ? installUpdate() : checkForUpdates()),
    },
    { type: 'separator' },
    { label: 'Quit', click: () => { isQuitting = true; app.quit(); } },
  ]);
  tray.setContextMenu(menu);
}

function createTray() {
  if (tray) return;
  const icon = appIcon() || nativeImage.createEmpty();
  tray = new Tray(icon);
  tray.on('click', showWindow);   // common on Windows/Linux
  updateTray();
}

function startHealthLoop() {
  if (healthTimer) return;
  const tick = async () => {
    const healthy = await isServiceHealthy();
    if (healthy) {
      setStatus('connected');
      connectWebSocket();
    } else {
      setStatus(serviceShouldRun ? 'connecting' : 'disconnected');
      // Respawn if it should be running but the process is gone.
      if (serviceShouldRun && !serviceProc) {
        spawnService();
      }
    }
  };
  healthTimer = setInterval(tick, HEALTH_INTERVAL_MS);
  tick();
}

// ---------------------------------------------------------------------------
// WebSocket metrics bridge
// ---------------------------------------------------------------------------
function connectWebSocket() {
  if (wsClient) return;
  // Always re-read the token: it changes whenever the service restarts.
  const token = getAuthToken(true);
  if (!token) {
    wsReconnectTimer = setTimeout(connectWebSocket, 2000);
    return;
  }

  wsClient = new WebSocket(`${WS_URL}?token=${token}`);

  wsClient.on('open', () => {
    console.log('Connected to Ambilight Metrics WS');
  });

  wsClient.on('message', (data) => {
    try {
      const msg = JSON.parse(data);
      if (mainWindow && !mainWindow.isDestroyed()) {
        mainWindow.webContents.send('metrics:update', msg);
      }
    } catch (e) {
      console.error("WS Parse error", e);
    }
  });

  wsClient.on('close', () => {
    wsClient = null;
    wsReconnectTimer = setTimeout(connectWebSocket, 2000);
  });

  wsClient.on('error', (err) => {
    console.error("WS Error:", err.message);
    if (wsClient) wsClient.close();
  });
}

// ---------------------------------------------------------------------------
// Auto-update (electron-updater → GitHub Releases)
// ---------------------------------------------------------------------------
function setUpdateState(next) {
  lastUpdateState = next;
  if (mainWindow && !mainWindow.isDestroyed()) {
    mainWindow.webContents.send('updater:status', next);
  }
  updateTray();
}

function checkForUpdates() {
  // Only meaningful in a packaged build with a published feed; dev runs have no
  // app-update.yml so a check would throw — guard and no-op instead.
  if (!app.isPackaged) {
    setUpdateState({ state: 'idle', detail: 'dev-build' });
    return;
  }
  try {
    autoUpdater.checkForUpdates();
  } catch (err) {
    console.error('[Updater] check failed:', err.message);
    setUpdateState({ state: 'error', detail: err.message });
  }
}

function installUpdate() {
  isQuitting = true;          // allow the window-close handler to actually exit
  try {
    autoUpdater.quitAndInstall();
  } catch (err) {
    console.error('[Updater] install failed:', err.message);
    isQuitting = false;
  }
}

function initAutoUpdater() {
  if (!app.isPackaged) return;   // no update feed in dev
  autoUpdater.autoDownload = true;
  autoUpdater.autoInstallOnAppQuit = true;

  autoUpdater.on('checking-for-update', () => setUpdateState({ state: 'checking' }));
  autoUpdater.on('update-available', (info) => setUpdateState({ state: 'available', version: info?.version }));
  autoUpdater.on('update-not-available', () => setUpdateState({ state: 'idle' }));
  autoUpdater.on('download-progress', (p) => setUpdateState({ state: 'downloading', percent: Math.round(p?.percent || 0) }));
  autoUpdater.on('update-downloaded', (info) => setUpdateState({ state: 'downloaded', version: info?.version }));
  autoUpdater.on('error', (err) => {
    // A missing/empty feed (no releases yet) surfaces here — keep it quiet.
    console.error('[Updater] error:', err?.message || err);
    setUpdateState({ state: 'error', detail: err?.message || String(err) });
  });

  // Initial check shortly after launch; ignore failures (e.g. no feed yet).
  setTimeout(checkForUpdates, 4000);
}

// ---------------------------------------------------------------------------
// Window + IPC
// ---------------------------------------------------------------------------
function createWindow() {
  // Reuse the existing window if it's only hidden (minimise-to-tray) so IPC
  // handlers are never registered twice.
  if (mainWindow && !mainWindow.isDestroyed()) {
    mainWindow.show();
    mainWindow.focus();
    return;
  }

  const saved = loadWindowState() || {}
  mainWindow = new BrowserWindow({
    width: saved.width || 1024,
    height: saved.height || 720,
    x: saved.x,
    y: saved.y,
    minWidth: 760,
    minHeight: 520,
    icon: appIcon(),
    title: APP_TITLE,
    webPreferences: {
      preload: path.join(__dirname, 'preload.cjs'),
      nodeIntegration: false,
      contextIsolation: true,
      backgroundThrottling: true,   // throttle timers/rAF when hidden
    },
    autoHideMenuBar: true,
  })

  // Keep the window title fixed — don't let the page's <title> override it.
  mainWindow.on('page-title-updated', (e) => { e.preventDefault(); mainWindow.setTitle(APP_TITLE) })
  mainWindow.setTitle(APP_TITLE)

  // Persist window bounds + tell the renderer to pause/resume work when hidden,
  // so a minimised-to-tray app costs ~no renderer CPU (the service keeps running).
  mainWindow.on('resize', saveWindowState)
  mainWindow.on('move', saveWindowState)
  mainWindow.on('hide', () => sendVisibility(false))
  mainWindow.on('minimize', () => sendVisibility(false))
  mainWindow.on('show', () => sendVisibility(true))
  mainWindow.on('restore', () => sendVisibility(true))

  // Minimise to tray instead of quitting when the window is closed.
  mainWindow.on('close', (e) => {
    if (!isQuitting) {
      e.preventDefault();
      mainWindow.hide();
    }
  });

  // --- Settings ---
  ipcMain.handle('api:settings:get', async () => fetchApi('/api/config'))
  ipcMain.handle('api:settings:update', async (e, settings) => fetchApi('/api/config', {
    method: 'PUT',
    body: JSON.stringify(settings)
  }))
  ipcMain.handle('api:settings:reload', async () => fetchApi('/api/config'))

  // --- Profiles ---
  ipcMain.handle('api:profiles:list', async () => fetchApi('/api/profiles'))
  ipcMain.handle('api:profiles:apply', async (e, name) => fetchApi(`/api/profiles/${name}/apply`, { method: 'POST' }))
  ipcMain.handle('api:profiles:save', async (e, name) => fetchApi(`/api/profiles/${name}`, { method: 'POST' }))
  ipcMain.handle('api:profiles:delete', async (e, name) => fetchApi(`/api/profiles/${name}`, { method: 'DELETE' }))

  // --- Effects ---
  ipcMain.handle('api:effects:setMode', async (e, mode, params) => fetchApi('/api/mode', {
    method: 'PUT',
    body: JSON.stringify({ mode, params })
  }))

  // --- Diagnostics / Effects ---
  ipcMain.handle('api:diagnostics:get', async () => fetchApi('/api/diagnostics'))
  ipcMain.handle('api:effects:list', async () => fetchApi('/api/effects'))

  // --- Devices ---
  ipcMain.handle('api:devices:list', async () => fetchApi('/api/devices'))
  ipcMain.handle('api:devices:scan', async () => fetchApi('/api/devices/scan', { method: 'POST' }))
  ipcMain.handle('api:devices:test', async (e, ip, port) => fetchApi('/api/devices/test', {
    method: 'POST',
    body: JSON.stringify({ ip, port })
  }))

  // --- Foreground app (auto-profile rules helper) ---
  ipcMain.handle('api:foreground:get', async () => fetchApi('/api/foreground'))

  // --- Auto-start (start on login) ---
  ipcMain.handle('api:autostart:get', async () => fetchApi('/api/autostart'))
  ipcMain.handle('api:autostart:enable', async () => fetchApi('/api/autostart/enable', { method: 'POST' }))
  ipcMain.handle('api:autostart:disable', async () => fetchApi('/api/autostart/disable', { method: 'POST' }))

  // --- Onboarding marker (~/.ambilight/onboarded) ---
  ipcMain.handle('app:onboarding:get', () => fs.existsSync(ONBOARDED_MARKER))
  ipcMain.handle('app:onboarding:complete', () => {
    try {
      if (!fs.existsSync(AMBILIGHT_DIR)) fs.mkdirSync(AMBILIGHT_DIR, { recursive: true })
      fs.writeFileSync(ONBOARDED_MARKER, new Date().toISOString())
      return true
    } catch (err) { console.error(err); return false }
  })

  // --- Profile import / export (native file dialogs) ---
  ipcMain.handle('api:profiles:export', async (e, name) => {
    const profile = await fetchApi(`/api/profiles/${name}`)
    const { canceled, filePath } = await dialog.showSaveDialog(mainWindow, {
      defaultPath: `${name}.json`,
      filters: [{ name: 'Ambilight Profile', extensions: ['json'] }],
    })
    if (canceled || !filePath) return { ok: false }
    fs.writeFileSync(filePath, JSON.stringify(profile, null, 2))
    return { ok: true, path: filePath }
  })
  ipcMain.handle('api:profiles:import', async () => {
    const { canceled, filePaths } = await dialog.showOpenDialog(mainWindow, {
      properties: ['openFile'],
      filters: [{ name: 'Ambilight Profile', extensions: ['json'] }],
    })
    if (canceled || !filePaths || !filePaths.length) return { ok: false }
    const file = filePaths[0]
    const data = JSON.parse(fs.readFileSync(file, 'utf8'))
    const name = path.basename(file, '.json')
    await fetchApi(`/api/profiles/${name}/import`, { method: 'POST', body: JSON.stringify(data) })
    return { ok: true, name }
  })

  // --- Auto-update ---
  ipcMain.handle('app:update:check', () => { checkForUpdates(); return lastUpdateState; })
  ipcMain.handle('app:update:install', () => { installUpdate(); return true; })
  ipcMain.handle('app:update:status', () => lastUpdateState)

  // --- Service control ---
  ipcMain.handle('api:service:status', () => lastStatus || 'disconnected')
  ipcMain.handle('api:service:start', async () => { await startService(); return true; })
  ipcMain.handle('api:service:stop', async () => { stopService(); setStatus('disconnected'); return true; })
  ipcMain.handle('api:service:restart', async () => { await restartService(); return true; })

  // --- Diagnostics & Logging ---
  ipcMain.handle('api:logs:read', async () => {
    try {
      if (fs.existsSync(LOG_FILE)) {
        const stats = fs.statSync(LOG_FILE);
        const start = Math.max(0, stats.size - 100000);
        return new Promise((resolve, reject) => {
          const stream = fs.createReadStream(LOG_FILE, { start, encoding: 'utf8' });
          let data = '';
          stream.on('data', chunk => data += chunk);
          stream.on('end', () => resolve(data));
          stream.on('error', err => reject(err));
        });
      }
      return "Log file not found.";
    } catch (err) {
      return `Error reading logs: ${err.message}`;
    }
  });

  ipcMain.handle('api:logs:openFolder', async () => {
    if (!fs.existsSync(LOG_DIR)) fs.mkdirSync(LOG_DIR, { recursive: true });
    shell.openPath(LOG_DIR);
  });

  ipcMain.handle('api:logs:clear', async () => {
    try {
      if (fs.existsSync(LOG_FILE)) fs.writeFileSync(LOG_FILE, '');
      return true;
    } catch (err) {
      console.error(err);
      return false;
    }
  });

  ipcMain.on('metrics:subscribe', () => { connectWebSocket(); });
  ipcMain.on('metrics:unsubscribe', () => {
    if (wsClient) { wsClient.close(); wsClient = null; }
    if (wsReconnectTimer) { clearTimeout(wsReconnectTimer); wsReconnectTimer = null; }
  });

  // Load UI
  if (process.env.VITE_DEV_SERVER_URL) {
    mainWindow.loadURL(process.env.VITE_DEV_SERVER_URL)
    mainWindow.webContents.openDevTools()
  } else {
    mainWindow.loadFile(path.join(__dirname, '../dist/index.html'))
  }
}

app.whenReady().then(async () => {
  createWindow()
  createTray()            // system tray with quick controls
  await startService();   // spawn (or adopt) the Python service
  startHealthLoop();      // supervise + drive status + connect WS
  connectWebSocket();
  initAutoUpdater();      // wire electron-updater (no-op in dev / no feed)

  app.on('activate', function () {
    showWindow()
  })
})

// With minimise-to-tray the app keeps running after the window is hidden.
// Only an explicit Quit (which sets isQuitting + app.quit) actually exits.
app.on('window-all-closed', function () {
  if (isQuitting && process.platform !== 'darwin') app.quit()
})

// Ensure we don't leave an orphaned service process behind.
app.on('before-quit', () => {
  if (healthTimer) { clearInterval(healthTimer); healthTimer = null; }
  stopService();
})
